version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: php_stage # PHPのステージを指定
    volumes:
      - ../:/app
    command: ["php-fpm"]

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx_stage # Nginxのステージを指定
    volumes:
      - ../:/app:ro
    ports:
      - "8000:80"
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=Passw0rd
    volumes:
      - laravel-db:/var/lib/mysql

volumes:
  laravel-db:
